name:                 pingfu
markdown:             kramdown
highlighter:          rouge
excerpt_separator:    <!--excerpt-->
permalink:            /:title/
url:                  "https://pingfu.net"
baseurl:              "/"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: :compressed
